"""empty message

Revision ID: 2f60a3189784
Revises: 
Create Date: 2022-10-21 03:28:59.891519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f60a3189784'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    op.add_column('user_info', sa.Column('email', sa.String(length=50), nullable=True))
    op.alter_column('user_info', 'username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user_info', 'password',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_index('username', table_name='user_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'user_info', ['username'], unique=False)
    op.alter_column('user_info', 'password',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_info', 'username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_column('user_info', 'email')
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_index('username', 'user', ['username'], unique=False)
    # ### end Alembic commands ###
